#pragma region KernalObject
enum_flags(KernalAccess   , DWORD           ,
	       Delete         = DELETE          ,
	       ReadCtl        = READ_CONTROL    ,
	       WriteDAC       = WRITE_DAC       ,
	       WriteOwner     = WRITE_OWNER     ,
	       Sync           = SYNCHRONIZE     ,
	       GenericRead    = GENERIC_READ    ,
	       GenericWrite   = GENERIC_WRITE   ,
	       GenericExecute = GENERIC_EXECUTE ,
	       GenericAll     = GENERIC_ALL     );
template<class AnyChild>
class KernalObject;
using Handle = KernalObject<void>;

class_chain_begin(KernalObject) {
	proxy_basetype(KernalObject, HANDLE, O);
	using Access = KernalAccess;

	~KernalObject() ret_to(Close());

	class_method(Close, void, (), to(Native::CloseHandle(self); proxy_obj = O));
	class_method(Compare, bool, (HANDLE h), as(Native::CompareObjectHandles(self, h))); /* const */

	//inline auto CopyTo() DuplicateHandle

public: // Property - Information
	/* W */ inline auto &Information(DWORD dwMask, DWORD dwFlags) ret_to_child(Native::SetHandleInformation(self, dwMask, dwFlags));
	/* R */ inline DWORD Information(DWORD dwMask) const ret_to(DWORD dwFlags = 0, Native::GetHandleInformation(self, &dwFlags), dwFlags &dwMask);
public: // Property - Inherit
	/* W */ inline auto &Inherit(bool bInherit) ret_to_child(Information(HANDLE_FLAG_INHERIT, bInherit ? HANDLE_FLAG_INHERIT : 0));
	/* R */ inline bool Inherit() const ret_as(Information(HANDLE_FLAG_INHERIT));
public: // Property - ProtectFromClose
	/* W */ inline auto &ProtectFromClose(bool bProtected) ret_to_child(Information(HANDLE_FLAG_PROTECT_FROM_CLOSE, bProtected ? HANDLE_FLAG_PROTECT_FROM_CLOSE : 0));
	/* R */ inline bool ProtectFromClose() const ret_as(Information(HANDLE_FLAG_PROTECT_FROM_CLOSE));
};
#pragma endregion

#pragma region Heaps
enum_flags(LocalAllocFlags, UINT          ,
		   Fixed          = LMEM_FIXED    ,
		   Modify         = LMEM_MODIFY   ,
		   Moveable       = LMEM_MOVEABLE ,
		   ZeroInit       = LMEM_ZEROINIT );
using LAF = LocalAllocFlags;
class Local {
public:
	using AllocFlags = LAF;
	static inline void *Alloc(SizeT size, LAF flags = LAF::Fixed) ret_to(auto ptr = LocalAlloc(flags.yield(), size), ptr);
	template<class AnyType>
	static inline AnyType *Alloc(LAF flags = LAF::Fixed) ret_to(auto ptr = (AnyType *)LocalAlloc(flags.yield(), sizeof(AnyType)), ptr);
	static inline void *Realloc(void *ptr, SizeT size, LAF flags = LAF::Fixed) ret_as(LocalReAlloc(ptr, size, flags.yield()));
	static inline void  Free(void *ptr) {
		if (ptr)
			nt_assert(!LocalFree(ptr));
	}
	static inline void *Lock(void *ptr) ret_as(LocalLock(ptr));
	static inline void Unlock(void *ptr) safe_ret_as(LocalUnlock(ptr));
	static inline void AutoFree(void *&ptr) ret_to(if (ptr) (Free(ptr), ptr = O));
} inline LocalHeap;

proxy_struct       (HeapSummaries, HEAP_SUMMARY        ) {
	proxy_prop_size(               cb           , DWORD);
	proxy_prop_sync(Allocated    , cbAllocated  , SizeT);
	proxy_prop_sync(Committed    , cbCommitted  , SizeT);
	proxy_prop_sync(Reserved     , cbReserved   , SizeT);
	proxy_prop_sync(MaxReserve   , cbMaxReserve , SizeT);};
enum_flags(HeapAllocFlag      , UINT                     ,
		   Fixed              = 0                        ,
		   GenerateExceptions = HEAP_GENERATE_EXCEPTIONS ,
		   NoSerialize        = HEAP_NO_SERIALIZE        ,
		   ZeroInit           = HEAP_ZERO_MEMORY         );
using HAF = HeapAllocFlag;
class Heap : public WandX::KernalObject<Heap> {
public:
	using Super = KernalObject<Heap>;
	using AllocFlags = HeapAllocFlag;
protected:
	//proxy_basetype(Heap);
	Heap(HANDLE hHeap) : Super(hHeap) {}
public:
	Heap() : Super(GetProcessHeap()) {}
	Heap(Nu) {}
	Heap(Heap & h) : Super(h) {}
	Heap(Heap && h) : Super(h) {}
	Heap(const Heap &) = delete;
	~Heap() ret_to(Destroy());
public:
	class CreateStruct {
		DWORD flOptions = 0;
		SIZE_T dwInitialSize = 0;
		SIZE_T dwMaximumSize = 0;
	public:
		CreateStruct() {}
	public:
		inline auto &MaximumSize(SIZE_T dwMaximumSize) ret_to_self(this->dwMaximumSize = dwMaximumSize);
		inline auto &InitialSize(SIZE_T dwInitialSize) ret_to_self(this->dwInitialSize = dwInitialSize);
		inline auto &Excutable() ret_to_self(this->flOptions |= HEAP_CREATE_ENABLE_EXECUTE);
		inline auto &GenerateException() ret_to_self(this->flOptions |= HEAP_GENERATE_EXCEPTIONS);
		inline auto &NoSerialize() ret_to_self(this->flOptions |= HEAP_NO_SERIALIZE);
	public:
		inline operator Heap() ret_as(HeapCreate(flOptions, dwInitialSize, dwMaximumSize));
	};
	static inline CreateStruct Create() ret_as({});
public:
	//	DWORD GetProcessHeaps(_In_ DWORD NumberOfHeaps, _Out_writes_to_(NumberOfHeaps, return) PHANDLE ProcessHeaps);
	inline bool Destroy() {
		if (Super::proxy_obj && Super::proxy_obj != GetProcessHeap())
			if (!HeapDestroy(Super::proxy_obj))
				return false;
		Super::proxy_obj = O;
		return true;
	}
	//inline void *Alloc(SizeT size, AllocFlags flags = AllocFlags::Fixed) safe_ret_as(auto h = HeapAlloc(self, flags.yield(), size), h);
	//inline void *Realloc(void *ptr, SizeT nSize, DWORD flags = 0) safe_ret_as((ptr = HeapReAlloc(self, flags, ptr, nSize)), ptr);
	//inline bool Free(void *ptr, DWORD flags = 0) ret_as(HeapFree(self, flags, ptr));
	//inline SizeT Size(const void *ptr, DWORD flags) const safe_ret_as(auto size = HeapSize(self, flags, ptr), size);
	//inline bool IsValid(const void *ptr, DWORD flags) const ret_as(HeapValidate(self, flags, ptr));
	//inline auto &Lock() safe_ret_as_self(HeapLock(self));
	//inline auto &Unlock() safe_ret_as_self(HeapUnlock(self));
	//	HeapWalk();
	//	SIZE_T HeapCompact(HANDLE hHeap, DWORD dwFlags);
public: // Property - Summaries
	//inline HeapSummaries Summaries(DWORD dwFlags = 0) const safe_ret_to(HeapSummaries s, ::HeapSummary(self, dwFlags, &s), s);
	//BOOL HeapSetInformation(
	//	_In_opt_ HANDLE HeapHandle,
	//	_In_ HEAP_INFORMATION_CLASS HeapInformationClass,
	//	_In_reads_bytes_opt_(HeapInformationLength) PVOID HeapInformation,
	//	_In_ SIZE_T HeapInformationLength);
	//BOOL HeapQueryInformation(
	//	_In_opt_ HANDLE HeapHandle,
	//	_In_ HEAP_INFORMATION_CLASS HeapInformationClass,
	//	_Out_writes_bytes_to_opt_(HeapInformationLength, *ReturnLength) PVOID HeapInformation,
	//	_In_ SIZE_T HeapInformationLength,
	//	_Out_opt_ PSIZE_T ReturnLength);
	using Super::operator=;
};
using CHeap = ProxyView<Heap>;
CHeap ThisHeap = Heap{};

template<class HeapType, class AnyType = void>
class AutoPointer {
	HeapType &heap;
	mutable AnyType *p = O;
public:
	using AllocFlags = typename HeapType::AllocFlags;
	AutoPointer() : heap(ThisHeap) {}
	explicit AutoPointer(SizeT size) : heap(ThisHeap), p(heap.Alloc(size)) {}
	AutoPointer(AllocFlags flags, SizeT size = SizeOf<AnyType>) : heap(ThisHeap), p((AnyType *)heap.Alloc(size, flags)) {}
	explicit AutoPointer(HeapType &heap) : heap(heap) {}
	~AutoPointer() ret_to(Free());
public:
	inline AnyType *Alloc(SizeT size = SizeOf<AnyType>) {
		if (size <= 0)
			Free();
		return (AnyType *)(p ? heap.Realloc(p, size) : heap.Alloc(size));
	}
	template<class AnyFlags>
	inline AnyType *Alloc(SizeT size, AnyFlags flags) {
		return (AnyType *)(p ? heap.Realloc(p, size, flags) : heap.Alloc(size, flags));
	}
	inline void Free() {
		if (p)
			heap.Free(p);
		p = O;
	}
public:
	inline AnyType *&operator*() ret_as(p);
	inline const AnyType *&operator*() const ret_as(p);
	inline AnyType *operator&() ret_as(p);
	inline const AnyType *operator&() const ret_as(p);
	inline AnyType *operator->() ret_as(p);
	inline const AnyType *operator->() const ret_as(p);
};
template<class AnyType = void>
using LocalPointer = AutoPointer<Local, AnyType>;
template<class AnyType = void>
using HeapPointer = AutoPointer<Heap, AnyType>;
#pragma endregion

#pragma region Time Types
enum_class(Locales                , LCID                      ,
		   Default                = LOCALE_CUSTOM_DEFAULT     ,
		   Unspecified            = LOCALE_CUSTOM_UNSPECIFIED ,
		   UIDefault              = LOCALE_CUSTOM_UI_DEFAULT  ,
		   Neutral                = LOCALE_NEUTRAL            ,
		   Invariant              = LOCALE_INVARIANT          );
enum_flags(TimeFormat             , DWORD                     ,
		   Default                = 0                         ,
		   NoMinutesOrSeconds     = TIME_NOMINUTESORSECONDS   ,
		   NoSecond               = TIME_NOSECONDS            ,
		   NoTimeMarker           = TIME_NOTIMEMARKER         ,
		   Force24H               = TIME_FORCE24HOURFORMAT    );
enum_flags(DateFormat             , DWORD                     ,
		   Default                = 0                         ,
		   ShortDate              = DATE_SHORTDATE            ,
		   LongDate               = DATE_LONGDATE             ,
		   UseAltCalendar         = DATE_USE_ALT_CALENDAR     ,
		   YearMonth              = DATE_YEARMONTH            ,
		   LTRReading             = DATE_LTRREADING           ,
		   RTLReading             = DATE_RTLREADING           ,
		   AutoLayout             = DATE_AUTOLAYOUT           ,
		   MonthDay               = DATE_MONTHDAY             );
proxy_struct(SystemTime, SYSTEMTIME) {
	SystemTime(Nu) {}
	SystemTime() ret_to(GetSystemTime(&self));
	SystemTime(const SYSTEMTIME &st) : Super(st) {}
public:
	proxy_prop_sync(Year         , wYear         , WORD);
	proxy_prop_sync(Month        , wMonth        , WORD);
	proxy_prop_sync(Day          , wDay          , WORD);
	proxy_prop_sync(Hour         , wHour         , WORD);
	proxy_prop_sync(Minute       , wMinute       , WORD);
	proxy_prop_sync(Second       , wSecond       , WORD);
	proxy_prop_sync(MilliSeconds , wMilliseconds , WORD);
public:
	static inline SystemTime LocalTime() ret_to(SystemTime st; GetLocalTime(&st), st);
public: // FormatDate
	template<bool IsUnicode = Native::IsUnicode>
	inline StringX<IsUnicode> FormatDate(Locales locale = Locales::Default, DateFormat df = DateFormat::Default, LPCXSTR<IsUnicode> lpFormat = O) const {
		int len = Native::GetDateFormat(locale.yield(), df.yield(), &self, lpFormat, O, 0);
		StringX<IsUnicode> str((SizeT)len - 1);
		Native::GetDateFormat(locale.yield(), df.yield(), &self, lpFormat, str, len);
		return right_cast(str);
	}
	inline StringA FormatDate(Locales locale, DateFormat df, LPCSTR lpFormat) const ret_as(FormatDate<false>(locale, df, lpFormat));
	inline StringW FormatDate(Locales locale, DateFormat df, LPCWSTR lpFormat) const ret_as(FormatDate<true>(locale, df, lpFormat));
	inline StringA FormatDateA(Locales locale = Locales::Default, DateFormat df = DateFormat::Default, LPCSTR lpFormat = O) const ret_as(FormatDate<false>(locale, df, lpFormat));
	inline StringW FormatDateW(Locales locale = Locales::Default, DateFormat df = DateFormat::Default, LPCWSTR lpFormat = O) const ret_as(FormatDate<true>(locale, df, lpFormat));
	inline StringW FormatDate(LPCWSTR lpLocaleName, DateFormat df = DateFormat::Default, LPCWSTR lpFormat = O) const {
		int len = Native::GetDateFormatEx(lpLocaleName, df.yield(), &self, lpFormat, O, 0, O);
		StringW str((SizeT)len - 1);
		Native::GetDateFormatEx(lpLocaleName, df.yield(), &self, lpFormat, str, len, O);
		return right_cast(str);
	}
public: // FormatTime
	template<bool IsUnicode = Native::IsUnicode>
	inline StringX<IsUnicode> FormatTime(Locales locale = Locales::Default, TimeFormat tf = TimeFormat::Default, LPCXSTR<IsUnicode> lpFormat = O) const {
		int len = Native::GetTimeFormat(locale.yield(), tf.yield(), &self, lpFormat, O, 0);
		StringX<IsUnicode> str((SizeT)len - 1);
		Native::GetTimeFormat(locale.yield(), tf.yield(), &self, lpFormat, str, len);
		return right_cast(str);
	}
	inline StringA FormatTime(Locales locale, TimeFormat tf, LPCSTR lpFormat) const ret_as(FormatTime<false>(locale, tf, lpFormat));
	inline StringW FormatTime(Locales locale, TimeFormat tf, LPCWSTR lpFormat) const ret_as(FormatTime<true>(locale, tf, lpFormat));
	inline StringA FormatTimeA(Locales locale = Locales::Default, TimeFormat tf = TimeFormat::Default, LPCSTR lpFormat = O) const ret_as(FormatTime<false>(locale, tf, lpFormat));
	inline StringW FormatTimeW(Locales locale = Locales::Default, TimeFormat tf = TimeFormat::Default, LPCWSTR lpFormat = O) const ret_as(FormatTime<true>(locale, tf, lpFormat));
	inline StringW FormatTime(LPCWSTR lpLocaleName, TimeFormat tf = TimeFormat::Default, LPCWSTR lpFormat = O) const {
		int len = Native::GetTimeFormatEx(lpLocaleName, tf.yield(), &self, lpFormat, O, 0);
		StringW str((SizeT)len - 1);
		Native::GetTimeFormatEx(lpLocaleName, tf.yield(), &self, lpFormat, str, len);
		return right_cast(str);
	}
public:
	template<bool IsUnicode = Native::IsUnicode>
	inline StringX<IsUnicode> toString() const {
		int lenDate = Native::GetDateFormat(LOCALE_CUSTOM_DEFAULT, 0, &self, (LPCXSTR<IsUnicode>)O, O, 0),
			lenTime = Native::GetTimeFormat(LOCALE_CUSTOM_DEFAULT, 0, &self, (LPCXSTR<IsUnicode>)O, O, 0);
		StringX<IsUnicode> str((SizeT)lenDate + lenTime - 1);
		Native::GetDateFormat(LOCALE_CUSTOM_DEFAULT, 0, &self, O, str, lenDate);
		Native::GetTimeFormat(LOCALE_CUSTOM_DEFAULT, 0, &self, O, ((LPXSTR<IsUnicode>)str) + lenDate, lenTime);
		str[lenDate - 1] = ' ';
		return right_cast(str);
	}
	inline StringA toStringA() const ret_as(toString<false>());
	inline StringW toStringW() const ret_as(toString<true>());

public:
	inline operator FILETIME() const safe_ret_to(FILETIME ft, SystemTimeToFileTime(&self, &ft), ft);
};
alias_of_type(SysTime, SystemTime);
#pragma endregion

#pragma region Message Wrapper
proxy_struct(Message, MSG) {
	Message() {}
	Message(const MSG &msg) : Super(msg) {}
	Message(HWND hwnd, UINT  message, WPARAM wParam, LPARAM lParam) : Super(MSG{ hwnd, message, wParam, lParam }) {}
public: // Property - Window
	/* W */ inline auto&Window(HWND hwnd) ret_as(self->hwnd);
public: // Property - ID
	proxy_prop_set(ID,message,UINT);
	template<class AnyEnum = UINT>
	/* R */ inline AnyEnum ID() const ret_as(reuse_cast<AnyEnum>(self->message));
public: // Property - ParamW
	template<class AnyType = WPARAM>
	/* W */ inline auto&ParamW(AnyType wParam) ret_to_self(self->wParam = small_cast<WPARAM>(wParam));
	template<class AnyType = WPARAM>
	/* R */ inline AnyType ParamW() const ret_as(big_cast<AnyType>(self->wParam));
public: // Property - ParamL
	template<class AnyType = WPARAM>
	/* W */ inline auto&ParamL(AnyType lParam) ret_to_self(self->lParam = small_cast<LPARAM>(lParam));
	template<class AnyType = WPARAM>
	/* R */ inline AnyType ParamL() const ret_as(big_cast<AnyType>(self->lParam));
public: // Property - Param
	template<class WParam = WPARAM, class LParam = LPARAM>
	/* W */ inline auto&Param(WParam wParam, LParam lParam) ret_to_self(self->wParam = small_cast<WPARAM>(wParam), self->lParam = small_cast<LPARAM>(lParam));
	proxy_prop_sync(Time,time,DWORD);
	inline auto &Point(POINT value) {
		(*this)->pt = (POINT)value; return (*this);
	}
	inline auto Point() const {
		return safe_c_cast<WandX::Point>((*this)->pt);
	};
public:
	inline bool Translate() const ret_as(Native::TranslateMessage(&self));
public:
	template<class RetType = LRESULT, bool IsUnicode = Native::IsUnicode>
	inline RetType Dispatch() const ret_as((RetType)DispatchMessage<IsUnicode>(&self));
public:
	template<class RetType = LRESULT, bool IsUnicode = Native::IsUnicode>
	inline RetType Send() const ret_as((RetType)SendMessage<IsUnicode>(self->hwnd, self->message, self->wParam, self->lParam));
public:
	template<bool IsUnicode = Native::IsUnicode>
	inline void Post() ret_to(Native::PostMessage<IsUnicode>(self->hwnd, self->message, self->wParam, self->lParam));
public:
	template<bool IsUnicode = Native::IsUnicode>
	inline bool Get(UINT wMsgFilterMin = 0, UINT wMsgFilterMax = 0) ret_as(Native::GetMessage<IsUnicode>(&self, O, wMsgFilterMin, wMsgFilterMax));
	template<bool IsUnicode = Native::IsUnicode>
	inline bool Get(HWND hwnd, UINT wMsgFilterMin = 0, UINT wMsgFilterMax = 0) ret_as(Native::GetMessage<IsUnicode>(&self, hwnd, wMsgFilterMin, wMsgFilterMax));
	template<bool IsUnicode = Native::IsUnicode>
	inline bool GetThread(UINT wMsgFilterMin = 0, UINT wMsgFilterMax = 0) ret_as(Native::GetMessage<IsUnicode>(&self, (HWND)-1, wMsgFilterMin, wMsgFilterMax));
public:
	template<bool IsUnicode = Native::IsUnicode>
	inline bool GetSafe(UINT wMsgFilterMin = 0, UINT wMsgFilterMax = 0) ret_as(Native::GetMessage<IsUnicode>(&self, O, wMsgFilterMin, wMsgFilterMax));
	template<bool IsUnicode = Native::IsUnicode>
	inline bool GetSafe(HWND hwnd, UINT wMsgFilterMin = 0, UINT wMsgFilterMax = 0) ret_as(Native::GetMessage<IsUnicode>(&self, hwnd, wMsgFilterMin, wMsgFilterMax));
	template<bool IsUnicode = Native::IsUnicode>
	inline bool GetThreadSafe(UINT wMsgFilterMin = 0, UINT wMsgFilterMax = 0) ret_as(Native::GetMessage<IsUnicode>(&self, (HWND)-1, wMsgFilterMin, wMsgFilterMax));
public:
	class Peeks {
		LPMSG lpMsg;
		HWND hwnd;
		UINT wMsgFilterMin;
		UINT wMsgFilterMax;
		UINT wRemoveMsg = PM_NOREMOVE;
	public:
		Peeks(LPMSG lpMsg, HWND hwnd, UINT wMsgFilterMin, UINT wMsgFilterMax) :
			lpMsg(lpMsg), hwnd(hwnd), wMsgFilterMin(wMsgFilterMin), wMsgFilterMax(wMsgFilterMax) {}
	public:
		inline auto&Remove() ret_to_self(this->wRemoveMsg |= PM_REMOVE);
		inline auto&NoYield() ret_to_self(this->wRemoveMsg |= PM_NOYIELD);
		inline auto&Input() ret_to_self(this->wRemoveMsg |= PM_QS_INPUT);
		inline auto&Paint() ret_to_self(this->wRemoveMsg |= PM_QS_PAINT);
		inline auto&MessagePost() ret_to_self(this->wRemoveMsg |= PM_QS_POSTMESSAGE);
		inline auto&MessageSend() ret_to_self(this->wRemoveMsg |= PM_QS_SENDMESSAGE);
	public:
		inline operator bool() ret_as(Native::PeekMessage<Native::IsUnicode>(lpMsg, hwnd, wMsgFilterMin, wMsgFilterMax, wRemoveMsg));
	};
	inline Peeks Peek(UINT wMsgFilterMin = 0, UINT wMsgFilterMax = 0) ret_as({ &self, O, wMsgFilterMin, wMsgFilterMax });
	inline Peeks Peek(HWND hwnd, UINT wMsgFilterMin = 0, UINT wMsgFilterMax = 0) ret_as({ &self, hwnd, wMsgFilterMin, wMsgFilterMax });
	inline Peeks PeekThread(UINT wMsgFilterMin = 0, UINT wMsgFilterMax = 0) ret_as({ &self, (HWND)-1, wMsgFilterMin, wMsgFilterMax });
};
alias_of_type(Msg, Message);
class MessageException : public Exception {
	Message msg;
public:
	using Super = Exception;
public:
	MessageException(const Exception &err, const Message &msg) : 
		Super(err), msg(msg) {}
public:
	inline const WandX::Msg &Msg() const ret_as(msg);
	inline const WandX::Msg &Message() const ret_as(msg);
public:
	inline operator const WandX::Msg &() const ret_as(msg);
};
alias_of_type(MsgException, MessageException);
#pragma endregion

#pragma region MsgBox
enum_flags(MB, int,
	Ok                  = MB_OK,
	OkCancel            = MB_OKCANCEL,
	AbortRetryIgnore    = MB_ABORTRETRYIGNORE,
	YesNoCancel         = MB_YESNOCANCEL,
	YesNo               = MB_YESNO,
	RetryCancel         = MB_RETRYCANCEL,
	CancelTryContinue   = MB_CANCELTRYCONTINUE,
	IconHand            = MB_ICONHAND,
	IconQuestion        = MB_ICONQUESTION,
	IconExclamation     = MB_ICONEXCLAMATION,
	IconAsterisk        = MB_ICONASTERISK,
	UserIcon            = MB_USERICON,
	IconWarning         = MB_ICONWARNING,
	IconError           = MB_ICONERROR,
	IconInformation     = MB_ICONINFORMATION,
	IconStop            = MB_ICONSTOP,
	DefButton1          = MB_DEFBUTTON1,
	DefButton2          = MB_DEFBUTTON2,
	DefButton3          = MB_DEFBUTTON3,
	DefButton4          = MB_DEFBUTTON4,
	ApplModal           = MB_APPLMODAL,
	SystemModal         = MB_SYSTEMMODAL,
	TaskModal           = MB_TASKMODAL,
	Help                = MB_HELP,
	NoFocus             = MB_NOFOCUS,
	SetForeground       = MB_SETFOREGROUND,
	DefaultDesktopOnly  = MB_DEFAULT_DESKTOP_ONLY,
	TopMost             = MB_TOPMOST,
	Right               = MB_RIGHT,
	RtlReading          = MB_RTLREADING,
	ServiceNotification = MB_SERVICE_NOTIFICATION);
inline auto MsgBox(LPCSTR lpCaption, LPCSTR lpText, MB type, HWND hParent = O)
	ret_as(Native::MessageBox(hParent, lpText, lpCaption, type.yield()));
inline auto MsgBox(LPCWSTR lpCaption, LPCWSTR lpText, MB type, HWND hParent = O)
	ret_as(Native::MessageBox(hParent, lpText, lpCaption, type.yield()));
inline auto MsgBox(LPCSTR lpCaption, LPCSTR lpText = O, HWND hParent = O)
	ret_as(Native::MessageBox(hParent, lpText, lpCaption, MB_OK));
inline auto MsgBox(LPCWSTR lpCaption = O, LPCWSTR lpText = O, HWND hParent = O)
	ret_as(Native::MessageBox(hParent, lpText, lpCaption, MB_OK));
inline int MsgBox(LPCSTR lpCaption, const Exception &err, HWND hParent = O)
	ret_as(MsgBox(lpCaption, toStringA(err), MB::IconError | MB::AbortRetryIgnore, hParent));
inline int MsgBox(LPCWSTR lpCaption, const Exception &err, HWND hParent = O)
	ret_as(MsgBox(lpCaption, toStringW(err), MB::IconError | MB::AbortRetryIgnore, hParent));
#pragma endregion

enum_class(Shows            , int                ,
		   Hide             = SW_HIDE            ,
		   ShowNormal       = SW_SHOWNORMAL      ,
		   Normal           = SW_NORMAL          ,
		   ShowMinimized    = SW_SHOWMINIMIZED   ,
		   ShowMaximized    = SW_SHOWMAXIMIZED   ,
		   Maximize         = SW_MAXIMIZE        ,
		   ShowNoActivate   = SW_SHOWNOACTIVATE  ,
		   Show             = SW_SHOW            ,
		   Minimize         = SW_MINIMIZE        ,
		   ShowMinNoActive  = SW_SHOWMINNOACTIVE ,
		   ShowNA           = SW_SHOWNA          ,
		   Restore          = SW_RESTORE         ,
		   ShowDefault      = SW_SHOWDEFAULT     ,
		   ForceMinimize    = SW_FORCEMINIMIZE   ,
		   Max              = SW_MAX             );

class RGBColor {
protected:
	COLORREF cr;
public:
	RGBColor(COLORREF color) : cr(color) {}
	RGBColor(BYTE red, BYTE green, BYTE blue) :
		cr(RGB(red, green, blue)) {}
public:
	inline BYTE Red() const ret_as(GetRValue(self));
	inline BYTE Green() const ret_as(GetGValue(self));
	inline BYTE Blue() const ret_as(GetBValue(self));
public:
	template<SizeT len>
	static inline ArrayOf<RGBColor, len> &Attach(ArrayOf<COLORREF, len> &ary) ret_as(ref_cast<ArrayOf<RGBColor, len>>(ary));
	inline operator COLORREF() const { return cr; }
	static inline RGBColor &Attach(COLORREF &clr) ret_as(*(RGBColor *)&clr);
};

template<class AnyType>
struct RangeOf {
	AnyType min, max;
public:
	RangeOf(const AnyType &a) : min(a), max(a) {}
	RangeOf(const AnyType &low, const AnyType &high) : min(low), max(high) {}
public: // Property - Low
	/* W */ inline auto&Low(const AnyType &low) ret_to_self(this->min = low);
	/* R */ inline auto Low() const ret_as(this->min);
public: // Property - High
	/* W */ inline auto&High(const AnyType &high) ret_to_self(this->max = high);
	/* R */ inline auto High() const ret_as(this->max);
public: // Property - Min
	/* W */ inline auto&Min(const AnyType &min) ret_to_self(this->min = min);
	/* R */ inline auto Min() const ret_as(this->min);
public: // Property - Max
	/* W */ inline auto&Max(const AnyType &max) ret_to_self(this->max = max);
	/* R */ inline auto Max() const ret_as(this->max);
public:	// Property - Start
	/* W */ inline auto&Start(const AnyType &start) ret_to_self(this->min = start);
	/* R */ inline auto Start() const ret_as(this->min);
public:	// Property - End
	/* W */ inline auto&End(const AnyType &end) ret_to_self(this->max = end);
	/* R */ inline auto End() const ret_as(this->max);
};

